#!/usr/bin/env bash
bash -n "$0" | exit 1

dbnm=$1
mach=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm default 'SELECT comdb2_host()'`

# this triggers cleanup_clnt code path and verifies that it doesn't race with done_sql_thread()
while true; do cdb2sql $dbnm --host $mach 'SYNTAX-ERROR'; done >/dev/null 2>&1 &
pid_sql=$!

# this verifies that sql-dump does not race with cleanup_clnt
while true; do cdb2sql $dbnm --host $mach 'exec procedure sys.cmd.send("sql dump")'; done >/dev/null 2>&1 &
pid_sql_dump=$!

sleep 60

kill -9 $pid_sql
kill -9 $pid_sql_dump

cdb2sql $dbnm --host $mach 'SELECT 1'
if [ $? != 0 ]; then
    echo "did not get a response from $mach???" >&2
    exit 1
fi

echo success
exit 0
