#!/bin/sh

bash -n "$0" | exit 1
dbnm=$1
host=`cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm default 'SELECT comdb2_host()'`
echo HOST IS $host
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm --host $host 'EXEC PROCEDURE sys.cmd.send("memstat debug on sqlite")'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm --host $host 'EXEC PROCEDURE sys.cmd.send("memstat debug start")'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm --host $host 'SELECT 1'
cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm --host $host 'EXEC PROCEDURE sys.cmd.send("memstat debug stop")'
stacks=`cdb2sql ${CDB2_OPTIONS} -s --tabs $dbnm --host $host 'EXEC PROCEDURE sys.cmd.send("memstat debug dump sqlite")'`
addr2line -fsp -e $COMDB2_EXE "$stack"
addr2line -fsp -e $COMDB2_EXE "$stack" | grep sql_statement_done
