#!/usr/bin/env bash

# Verify that a chunked transaction returns total query effects from all chunks

bash -n "$0" | exit 1

dbnm=$1

set -e

cat << EOF | cdb2sql --showeffects ${CDB2_OPTIONS} -s --tabs $dbnm default - >output.actual 2>&1
DROP TABLE IF EXISTS t1
CREATE TABLE t1 (i INT)\$\$
INSERT INTO t1 VALUES(1),(2),(3),(4)
SET TRANSACTION CHUNK 1
BEGIN
DELETE FROM t1 WHERE 1
COMMIT
EOF

diff output.actual output.expected
