#!/usr/bin/env bash

set -e

dbnm=$1
dbdir=${DBDIR}
bindir=`dirname $COMDB2_EXE`
total=2500
delrange=25
ndels=200

if [ "$tier" = "" ]; then
    tier='default'
fi

echo "DBNAME is $dbnm"
echo "DBDIR is $dbdir"
echo "BIN DIR is $bindir"
echo "tier is $tier"

mynode=`hostname`
myfnode=`hostname -f`
leader=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "select host from comdb2_cluster where is_master='Y'"`

echo "I AM $mynode"
echo "LEADER is $leader"

echo '------ Test 1.1 - deleting random overflow pages ------'
cdb2sql $dbnm --host $leader - <<EOF
DROP TABLE IF EXISTS t11
CREATE TABLE t11 (b blob)\$\$
INSERT INTO t11 SELECT randomblob(16*1024) FROM generate_series(1, $total)
EXEC PROCEDURE sys.cmd.send('flush')
SELECT sleep(5)
EOF

szbefore=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "SELECT bytes FROM comdb2_tablesizes WHERE tablename='t11'"`
cdb2sql $dbnm --host $leader "EXEC PROCEDURE sys.cmd.send('stat size')" 

for i in `seq 1 $ndels`; do
    cdb2sql ${CDB2_OPTIONS} $dbnm $tier "DELETE FROM t11 LIMIT $RANDOM%($delrange) OFFSET $RANDOM%($total)" >/dev/null
done

echo 'done deleting'

cdb2sql $dbnm --host $leader - <<EOF
EXEC PROCEDURE sys.cmd.send('evict_from_cache t11')
SELECT COUNT(*) FROM t11
EXEC PROCEDURE sys.cmd.send('flush')
EOF

nresizes=0
# wait for at least 10 resizes, or size has reduced at least half
while [ $nresizes -lt 10 ]; do

    cdb2sql $dbnm --host $leader "EXEC PROCEDURE sys.cmd.send('stat pgmv')"
    cdb2sql $dbnm --host $leader "EXEC PROCEDURE sys.cmd.send('stat size')"
    sleep 30
    nresizes=`cdb2sql --tabs $dbnm --host $leader "EXEC PROCEDURE sys.cmd.send('stat pgmv')" | grep nresizes | cut -d ' ' -f2`
    echo num resizes $nresizes

    szafter=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "SELECT bytes FROM comdb2_tablesizes WHERE tablename='t11'"`
    echo "size before: $szbefore; size after: $szafter"
    success=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "SELECT $szbefore/$szafter >= 2"`
    if [ $success = "1" ]; then
        break;
    fi
done

# pause the background thread. testsuite needs to verify btrees
cdb2sql ${CDB2_OPTIONS} $dbnm --host $leader "EXEC PROCEDURE sys.cmd.send('pgmv_thr_pause 1')"

szafter=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "SELECT bytes FROM comdb2_tablesizes WHERE tablename='t11'"`
echo "size before: $szbefore; size after: $szafter"

cdb2sql ${CDB2_OPTIONS} $dbnm $tier "SELECT $szafter/$szbefore.0 AS ratio"
success=`cdb2sql --tabs ${CDB2_OPTIONS} $dbnm $tier "SELECT $szbefore/$szafter >= 2"`

if [ $success != "1" ]; then
    echo "expected less than half of original table size" >&2
    exit 1
fi
