#!/usr/bin/env bash
bash -n "$0" | exit 1

db=$1

# Generate Java key store and trust store
rm -f ${TESTDIR}/client-keystore.pkcs12 ${TESTDIR}/keystore ${TESTDIR}/truststore

openssl pkcs12 -export \
        -in ${TESTDIR}/client.crt \
        -inkey ${TESTDIR}/client.key \
        -name cdb2clikey \
        -passout pass:cdb2jdbctest \
        -out ${TESTDIR}/client-keystore.pkcs12
keytool -noprompt -importkeystore \
        -srckeystore ${TESTDIR}/client-keystore.pkcs12 \
        -srcstoretype pkcs12 \
        -srcstorepass cdb2jdbctest \
        -destkeystore ${TESTDIR}/keystore \
        -deststoretype JKS \
        -deststorepass cdb2jdbctest
keytool -noprompt -importcert \
        -alias cdb2ca \
        -file ${TESTDIR}/root.crt \
        -keystore ${TESTDIR}/truststore \
        -storepass cdb2jdbctest

chmod 644 ${TESTDIR}/keystore ${TESTDIR}/truststore

export envSkipTests='false'
export envTestDatabase=$db
export envSSLTestDatabase=$db
export envSSLCertPath=${TESTDIR}
export envSSLCertPass='cdb2jdbctest'
export envTestCluster=$(sed -i 's/ /,/g' ${CLUSTER})

mvn -f ${SRCHOME}/cdb2jdbc/pom.xml \
        -Denv.skipTests=$(envSkipTests) \
        -DargLine="-Dcdb2jdbc.test.database=$(envTestDatabase) \
        -Dcdb2jdbc.test.cluster=$(envTestCluster) \
        -Dcdb2jdbc.test.ssldatabase=$(envSSLTestDatabase) \
        -Dcdb2jdbc.test.sslcertpath=$(envSSLCertPath) \
        -Dcdb2jdbc.test.sslcertpass=$(envSSLCertPass)" \
clean install
